# Generated by Django 4.2 on 2023-04-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=43)),
                ('client_secret', models.CharField(max_length=43)),
            ],
        ),
        migrations.CreateModel(
            name='MastoApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('access_token', models.CharField(max_length=43)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastoapi.instance')),
            ],
        ),
    ]
